"""Vacancy.external_id: add expanded constraint and part index

Revision ID: 3e196d013b87
Revises: 0001_create_vacancies
Create Date: 2026-03-15 14:57:05.058040
"""

from alembic import op
import sqlalchemy as sa


revision = '3e196d013b87'
down_revision = '0001_create_vacancies'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_vacancies_external_id'), 'vacancies', type_='unique')
    op.create_index('uq_vacancies_external_id', 'vacancies', ['external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_vacancies_external_id', table_name='vacancies', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_vacancies_external_id'), 'vacancies', ['external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
